DROP TABLE SEAT;
DROP TABLE BUS_GRADE;
DROP TABLE MEMBER;
DROP TABLE RESERVATION;
DROP TABLE DRIVE;
DROP TABLE BUS;
DROP TABLE BUS_TERMINAL;
DROP TABLE EMPLOYEE;
DROP TABLE BUS_COMPANY;

--  사용자
CREATE TABLE MEMBER (
   M_ID CHAR(20) NOT NULL,
   M_PW VARCHAR2(30) NOT NULL,
   M_NAME VARCHAR2(10) NOT NULL,
   M_TELNO VARCHAR2(11) NULL,
   M_ADD VARCHAR2(50) NOT NULL,
   M_MILEAGE NUMBER(6) DEFAULT '0'
);

--  사용자
ALTER TABLE MEMBER
   ADD CONSTRAINT PK_MEMBER --  사용자 기본키
   PRIMARY KEY (
   M_ID -- 아이디
   );

-- 터미널
CREATE TABLE BUS_TERMINAL (
   T_NO CHAR(4) NOT NULL,
   T_NAME VARCHAR(30) NOT NULL
);

-- 터미널
ALTER TABLE BUS_TERMINAL
   ADD CONSTRAINT PK_BUS_TERMINAL -- 터미널 기본키
   PRIMARY KEY (
   T_NO -- 터미널코드
   );

-- 버스
CREATE TABLE BUS (
   B_CODE CHAR(6) NOT NULL,
   E_ID CHAR(20) NOT NULL,
   C_CODE CHAR(6) NOT NULL,
   B_NUM NUMBER(2) NOT NULL
);

-- 버스
ALTER TABLE BUS
   ADD CONSTRAINT PK_BUS -- 버스 기본키
   PRIMARY KEY (
   B_CODE -- 버스코드
   );

-- 좌석
CREATE TABLE SEAT (
   S_CODE CHAR(6) NOT NULL,
   B_CODE CHAR(6) NOT NULL,
   S_RESERVATION CHAR(1) NOT NULL
);

-- 좌석
ALTER TABLE SEAT
   ADD CONSTRAINT PK_SEAT -- 좌석 기본키
   PRIMARY KEY (
   S_CODE, -- 좌석코드
   B_CODE  -- 버스코드
   );

-- 버스등급
CREATE TABLE BUS_GRADE (
   G_CLASS CHAR(8) NOT NULL,
   G_PRICE NUMBER(10) NOT NULL,
   B_CODE CHAR(6) NULL,
   E_ID CHAR(20) NULL,
   C_CODE CHAR(6) NULL
);

-- 버스등급
ALTER TABLE BUS_GRADE
   ADD CONSTRAINT PK_BUS_GRADE -- 버스등급 기본키
   PRIMARY KEY (
   G_CLASS -- 등급명
   );

-- 버스회사관리
CREATE TABLE BUS_COMPANY (
   C_CODE CHAR(6) NOT NULL,
   C_NAME VARCHAR2(20) NOT NULL,
   C_ADDRESS VARCHAR2(100) NULL,
   C_TELNO NUMBER(11) NULL
);

-- 버스회사관리
ALTER TABLE BUS_COMPANY
   ADD CONSTRAINT PK_BUS_COMPANY -- 버스회사관리 기본키
   PRIMARY KEY (
   C_CODE -- 회사코드
   );

-- 직원
CREATE TABLE EMPLOYEE (
   E_ID CHAR(20) NOT NULL,
   C_CODE CHAR(6) NOT NULL,
   E_PW VARCHAR2(30) NOT NULL,
   E_NAME VARCHAR2(30) NOT NULL,
   E_TELNO NUMBER(11) NULL
);

-- 직원
ALTER TABLE EMPLOYEE
   ADD CONSTRAINT PK_EMPLOYEE -- 직원 기본키
   PRIMARY KEY (
   E_ID -- 아이디
   );

-- 예매
CREATE TABLE RESERVATION (
   R_NUM VARCHAR2(15) NOT NULL,
   D_NUM NUMBER(3) NULL,
   M_ID CHAR(20) NULL
);

-- 예매
ALTER TABLE RESERVATION
   ADD CONSTRAINT PK_RESERVATION -- 예매 기본키
   PRIMARY KEY (
   R_NUM -- 예매번호
   );

-- 운행
CREATE TABLE DRIVE (
   D_NUM NUMBER(3) NOT NULL,
   D_DEPARTTIME DATE NOT NULL,
   D_ARRIVETIME DATE NOT NULL,
   B_CODE CHAR(6) NULL,
   T_DEPART CHAR(4) NULL,
   T_ARRIVE CHAR(4) NULL,
   E_ID CHAR(20) NULL,
   C_CODE CHAR(6) NULL
);

-- 운행
ALTER TABLE DRIVE
   ADD CONSTRAINT PK_DRIVE -- 운행 기본키
   PRIMARY KEY (
   D_NUM -- 운행번호
   );

-- 버스
ALTER TABLE BUS
   ADD CONSTRAINT FK_EMPLOYEE_TO_BUS -- 직원 -> 버스
   FOREIGN KEY (
   E_ID -- 아이디
   )
   REFERENCES EMPLOYEE ( -- 직원
   E_ID -- 아이디
   );

-- 버스
ALTER TABLE BUS
   ADD CONSTRAINT FK_BUS_COMPANY_TO_BUS -- 버스회사관리 -> 버스
   FOREIGN KEY (
   C_CODE -- 회사코드
   )
   REFERENCES BUS_COMPANY ( -- 버스회사관리
   C_CODE -- 회사코드
   );

-- 좌석
ALTER TABLE SEAT
   ADD CONSTRAINT FK_BUS_TO_SEAT -- 버스 -> 좌석
   FOREIGN KEY (
   B_CODE -- 버스코드
   )
   REFERENCES BUS ( -- 버스
   B_CODE -- 버스코드
   );

-- 버스등급
ALTER TABLE BUS_GRADE
   ADD CONSTRAINT FK_BUS_TO_BUS_GRADE -- 버스 -> 버스등급
   FOREIGN KEY (
   B_CODE -- 버스코드
   )
   REFERENCES BUS ( -- 버스
   B_CODE -- 버스코드
   );

-- 직원
ALTER TABLE EMPLOYEE
   ADD CONSTRAINT FK_BUS_COMPANY_TO_EMPLOYEE -- 버스회사관리 -> 직원
   FOREIGN KEY (
   C_CODE -- 회사코드
   )
   REFERENCES BUS_COMPANY ( -- 버스회사관리
   C_CODE -- 회사코드
   );

-- 예매
ALTER TABLE RESERVATION
   ADD CONSTRAINT FK_DRIVE_TO_RESERVATION -- 운행 -> 예매
   FOREIGN KEY (
   D_NUM -- 운행번호
   )
   REFERENCES DRIVE ( -- 운행
   D_NUM -- 운행번호
   );

-- 예매
ALTER TABLE RESERVATION
   ADD CONSTRAINT FK_MEMBER_TO_RESERVATION --  사용자 -> 예매
   FOREIGN KEY (
   M_ID -- 아이디
   )
   REFERENCES MEMBER ( --  사용자
   M_ID -- 아이디
   );

-- 운행
ALTER TABLE DRIVE
   ADD CONSTRAINT FK_BUS_TO_DRIVE -- 버스 -> 운행
   FOREIGN KEY (
   B_CODE -- 버스코드
   )
   REFERENCES BUS ( -- 버스
   B_CODE -- 버스코드
   );

-- 운행
ALTER TABLE DRIVE
   ADD CONSTRAINT FK_BUS_TERMINAL_TO_DRIVE -- 터미널 -> 운행
   FOREIGN KEY (
   T_DEPART -- 출발지
   )
   REFERENCES BUS_TERMINAL ( -- 터미널
   T_NO -- 터미널코드
   );

-- 운행
ALTER TABLE DRIVE
   ADD CONSTRAINT FK_BUS_TERMINAL_TO_DRIVE2 -- 터미널 -> 운행2
   FOREIGN KEY (
   T_ARRIVE -- 도착지
   )
   REFERENCES BUS_TERMINAL ( -- 터미널
   T_NO -- 터미널코드
   );